load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir[File.dirname(__FILE__) + '/../**/recipes/*.rb'].each { |plugin| load(plugin) }

load File.dirname(__FILE__) + '/config/deploy.rb' # remove this line to skip loading any of the default tasks